import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <header className="bg-gray-900 text-white py-4">
            <nav className="container mx-auto flex justify-between items-center">
              <a href="/" className="text-2xl font-bold tracking-tight">Virtual Horses</a>
              <ul className="flex space-x-4">
                <li><a href="/" className="hover:text-gray-300">Home</a></li>
                <li><a href="/race" className="hover:text-gray-300">Races</a></li>
              </ul>
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Connect Wallet
              </button>
            </nav>
          </header>
          <main className="bg-gray-50 min-h-screen">
            {children}
          </main>
          {/* <footer className="bg-gray-900 text-white py-4 fixed bottom-0 left-0 right-0">
            <div className="container mx-auto text-center">
              <p>&copy; 2023 Virtual Horses. All rights reserved.</p>
            </div>
          </footer> */}
        </div>
      </body>
    </html>
  )
}
